version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=flaskdb
      - DB_USER=flaskuser
      - DB_PASS=flaskpass
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    ports:
      - "5432:5432"
